version: "3.9"

services:
  db:
    container_name: entrega-sprint5-db
    image: postgres:12
    ports:
      - 45432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=users_database
